### ISSUE TITLE
create images folder and add images

### ISSUE THREAD

**Issue by amitoj-singh** [amitoj-singh/personal-portfolio#2]
- Create a new folder 'images' in the root directory.
- Download all project images and add them to the images folder. (Name images properly).
- change src/index.html to provide relative path to images from images folder.

**Please go through [Contributing Guidelines](https://github.com/amitoj-singh/personal-portfolio/blob/master/Contributing.md) in case you feel like contributing🙂**

**Comment by Sheitak** [comment]
Hello @amitoj-singh , Alright, I'll take care of doing that if you agree,

**Comment by amitoj-singh** [comment]
> Hello @amitoj-singh , Alright, I'll take care of doing that if you agree,

Yes, sure. Good to go

**Comment by Sheitak** [comment]
It's okay for me
